using System;

namespace Real_Estate_Agencies.Model
{
    public class Payment
    {
        public int PaymentId { get; set; }   // Auto-generated by SQL
        public int SaleId { get; set; }      // Comes from Sale
        public string PaymentType { get; set; }
        public decimal Amount { get; set; }
        public DateTime PaymentDate { get; set; }
    }
}
