using System;
using System.Windows;
using Real_Estate_Agencies.Model;

namespace Real_Estate_Agencies
{
    public partial class AddPaymentWindow : Window
    {
        public Payment NewPayment { get; private set; }
        private int SaleId;

        public AddPaymentWindow(int saleId)
        {
            InitializeComponent();
            SaleId = saleId; // store the SaleId passed in
        }

        private void Save_Click(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrWhiteSpace(TxtAmount.Text) ||
                PaymentDatePicker.SelectedDate == null ||
                PaymentMethodComboBox.SelectedItem == null)
            {
                MessageBox.Show("⚠ Please fill in all fields.", "Validation Error",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            if (!decimal.TryParse(TxtAmount.Text, out decimal amount))
            {
                MessageBox.Show("⚠ Amount must be a valid number.", "Invalid Input",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            NewPayment = new Payment
            {
                // PaymentId will be auto-generated by SQL
                SaleId = SaleId, // ✅ automatically set from parent
                Amount = amount,
                PaymentDate = PaymentDatePicker.SelectedDate.Value,
                PaymentType = ((System.Windows.Controls.ComboBoxItem)PaymentMethodComboBox.SelectedItem).Content.ToString()
            };

            DialogResult = true;
            Close();
        }

        private void Cancel_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
            Close();
        }
    }
}
